// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABveRpQS6XjxKLwhRW8qr6sCrSb7NFQsI',
    appId: '1:570522783647:web:57b31d73a4c073a587f7aa',
    messagingSenderId: '570522783647',
    projectId: 'attendance-system-8e5a5',
    authDomain: 'attendance-system-8e5a5.firebaseapp.com',
    storageBucket: 'attendance-system-8e5a5.appspot.com',
    measurementId: 'G-Z0DR32CMZ8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHgmEmxEGoYizEbdCEWnUbiBhaNdLEYFk',
    appId: '1:570522783647:ios:516b0600b4c7fe5f87f7aa',
    messagingSenderId: '570522783647',
    projectId: 'attendance-system-8e5a5',
    storageBucket: 'attendance-system-8e5a5.appspot.com',
    iosBundleId: 'com.example.attendancesystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABveRpQS6XjxKLwhRW8qr6sCrSb7NFQsI',
    appId: '1:570522783647:web:4cf05d9f93f57fbb87f7aa',
    messagingSenderId: '570522783647',
    projectId: 'attendance-system-8e5a5',
    authDomain: 'attendance-system-8e5a5.firebaseapp.com',
    storageBucket: 'attendance-system-8e5a5.appspot.com',
    measurementId: 'G-SP4MJJHB0E',
  );
}
